8jrogram_options:
  tray: true             # Show tray icon
  notify: true           # Enable notifications
  automount: true        # Enable automatic mounting
  file_manager: dolphin  # Program to open mounted directories

device_config:
  - id_label: ["Media"]
    options: [noatime]
    ignore: false
    automount: true

